yahooFinanceUrl = "https://finance.yahoo.com"
stocksJson = "stocks.json"
countries = {
    "ARG" : "Argentina",
    "AUT" : "Austria",
    "AUS" : "Australia",
    "BEL" : "Belgium",
    "BRA" : "Brazil",
    "CAN" : "Canada",
    "CHE" : "Switzerland",
    "CHL" : "Chile",
    "CHN" : "China",
    "CZE" : "Czechia",
    "GER" : "Germany",
    "DNK" : "Denmark",
    "EST" : "Estonia",
    "EGY" : "Egypt",
    "ESP" : "Spain",
    "FIN" : "Finland",
    "FRA" : "France",
    "GBR" : "United Kingdom",
    "GRC" : "Greece",
    "HKG" : "Hong Kong SAR China",
    "HUN" : "Hungary",
    "IDN" : "Indonesia",
    "IRL" : "Ireland",
    "ISR" : "Israel",
    "IND" : "India",
    "ISL" : "Iceland",
    "ITA" : "Italy",
    "JPN" : "Japan",
    "KOR" : "South Korea",
    "KWT" : "Kuwait",
    "LKA" : "Sri Lanka",
    "LTU" : "Lithuania",
    "LVA" : "Latvia",
    "MEX" : "Mexico",
    "MYS" : "Malaysia",
    "NLD" : "Netherlands",
    "NOR" : "Norway",
    "NZL" : "New Zealand",
    "PER" : "Peru",
    "PHL" : "Philippines",
    "PAK" : "Pakistan",
    "POL" : "Poland",
    "PRT" : "Portugal",
    "QAT" : "Qatar",
    "RUS" : "Russia",
    "SAU" : "Saudi Arabia",
    "SWE" : "Sweden",
    "SGP" : "Singapore",
    "SUR" : "Suriname",
    "THA" : "Thailand",
    "TUR" : "Turkey",
    "TWN" : "Taiwan",
    "USA" : "United States",
    "VEN" : "Venezuela",
    "VNM" : "Vietnam",
    "ZAF" : "South Africa",
}
